# Leverage main site's theme
remote_theme: SecurEth/secureth.github.io

title: SecurEth Guidelines
author: The SecurEth Foundation
description: Smart Contract Development Guidelines for Ethereum
url: "https://secureth.org/guidelines/"
lang: en
timezone: UTC
exclude:
  - README.md
  - LICENSE
